//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleStock.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Units { get; set; }
        public decimal Cost { get; set; }
        public string Price { get; set; }
        public int StoreId { get; set; }
        public int ProductCategoryId { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
